server:
  port: 8766

spring:
  application:
    name: micro-xxljob-client

xxl:
  admin:
    addresses: http://127.0.0.1:8765/xxl-job-admin
  job:
    executor:
      ip: ''
      logretentiondays: '30'
      appname: micro-xxljob-client
      logpath: /data/applogs/xxl-job/jobhandler
      address: ''
      port: '18766'
    accessToken: default_token

management:
  endpoints:
    web:
      base-path: /

logging:
  level:
    root: info
    com.felix: debug
  customize:
    appender: console

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: FULL