server:
  port: 8764

spring:
  application:
    name: micro-express

management:
  endpoints:
    web:
      base-path: /

logging:
  level:
    root: info
    com.felix: debug
  customize:
    appender: console


feign:
  client:
    config:
      default:
        loggerLevel: FULL