server:
  port: 8861

spring:
  application:
    name: micro-minio

minio:
  accessKey: minio
  secretKey: minio123
  bucket: bucket-felix
  endpoint: http://192.168.197.101:9000
  readPath: http://192.168.197.101:9000

management:
  endpoints:
    web:
      base-path: /

logging:
  level:
    root: info
    com.felix: debug
  customize:
    appender: console


feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: FULL