server:
  port: 8761

eureka:
  server:
    #eureka server刷新readCacheMap的时间
    #把readWriteCacheMap的缓存更新到readCacheMap上周期
    response-cache-update-interval-ms: 10000 #default 30*1000
    response-cache-auto-expiration-in-seconds: 60 #default 180s
    eviction-interval-timer-in-ms: 20000 #default 60*1000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://admin:123456@127.0.0.1:8761/eureka/
  environment: template
  datacenter: cloud

management:
  endpoints:
    web:
      base-path: /

spring:
  application:
    name: micro-eureka
  security:
    user:
      name: admin
      password: 123456

logging:
  appender: console
  path: /data/logs
  pattern:
    level: info