server:
  port: 8862

spring:
  application:
    name: micro-mysql
  member:
    datasource:
      jdbc-url: jdbc:mysql://${common.mysql.url}:3306/micro_member?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
      username: ${common.mysql.username}
      password: ${common.mysql.password}
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        validation-timeout: '1000'
        idle-timeout: '30000'
        maximum-pool-size: '10'
        auto-commit: 'true'
        connection-timeout: '10000'
        pool-name: HikariCP
        max-lifetime: '900000'
        connection-test-query: SELECT 1
        minimum-idle: '3'
  transaction:
    datasource:
      jdbc-url: jdbc:mysql://${common.mysql.url}:3306/micro_transaction?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
      username: ${common.mysql.username}
      password: ${common.mysql.password}
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        validation-timeout: '1000'
        idle-timeout: '30000'
        maximum-pool-size: '10'
        auto-commit: 'true'
        connection-timeout: '10000'
        pool-name: HikariCP
        max-lifetime: '900000'
        connection-test-query: SELECT 1
        minimum-idle: '3'

management:
  endpoints:
    web:
      base-path: /

logging:
  level:
    root: info
    com.felix: debug
  customize:
    appender: console

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: FULL